# Generated by Django 5.1.1 on 2024-09-19 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.genero')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('fecha_alquiler', models.DateTimeField()),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.videojuego')),
            ],
        ),
    ]
